id = "wxml"
name = "WXML"
description = "WXML (WeiXin Markup Language) support for Zed."
version = "0.1.0"
schema_version = 1
authors = ["BlockLune <39331194+BlockLune@users.noreply.github.com>"]
repository = "https://github.com/BlockLune/zed-wxml"

[grammars.wxml]
repository = "https://github.com/BlockLune/tree-sitter-wxml"
rev = "997bd575d9d03669baaf2f097031828c039f43c4"
